# Generated by Django 5.1.2 on 2024-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_options_remove_event_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='main.tag'),
        ),
    ]
