# Generated by Django 5.1.2 on 2024-12-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in-person', 'In-Person'), ('hybrid', 'Hybrid')], default='in-person', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('self-funded', 'Self-funded')], default='self-funded', max_length=20),
        ),
    ]
