# Generated by Django 5.1.2 on 2024-12-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_location_type_event_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
