# Generated by Django 5.1.2 on 2024-12-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='line_of_service',
            field=models.CharField(blank=True, choices=[('Audit', 'Audit'), ('Consulting', 'Consulting'), ('Tax', 'Tax'), ('Advisory', 'Advisory'), ('Assurance', 'Assurance')], max_length=50, null=True),
        ),
    ]
