# Generated by Django 5.0.6 on 2025-02-12 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
