# Generated by Django 5.1.6 on 2025-02-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_announcement_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='line_of_service',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Audit', 'Audit'), ('Consulting', 'Consulting'), ('Tax', 'Tax'), ('Advisory', 'Advisory'), ('Assurance', 'Assurance')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('self-funded', 'Self-funded'), ('paid-for', 'Paid For')], default='self-funded', max_length=20),
        ),
    ]
