# Generated by Django 5.1.6 on 2025-03-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_customuser_line_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to='main.event'),
        ),
    ]
