# Generated by Django 5.1.6 on 2025-03-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_eventsignup_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
