# Generated by Django 5.1.6 on 2025-03-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_eventinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinterest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
